const portfolioData = [
  {
    id: 1,
    title: "LanghamTrading Profitabel Stock Picks",
    categories: ["ui-ux", "website"],
    image: "/Envobyte/ui-1.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 2,
    title: "Improve your Skill With This Way",
    categories: ["ui-ux", "website"],
    image: "/Envobyte/ui2.png",
    logos: ["/Envobyte/wordpress.png", "/Envobyte/seo.png"],
  },
  {
    id: 3,
    title: "Grow Your Skills, Define Your Future",
    categories: ["website", "banner-design"],
    image: "/Envobyte/ui3.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 4,
    title: "Email Marketing Software to Engage Your Audience",
    categories: ["ui-ux", "seo"],
    image: "/Envobyte/ui4.png",
    logos: ["/Envobyte/wordpress.png", "/Envobyte/seo.png"],
  },
  {
    id: 5,
    title: "Ask Anything You Desire, Our Chat Holds the Solutions",
    categories: ["ui-ux", "website"],
    image: "/Envobyte/ui5.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 6,
    title: "DIGITAL DESIGN AGENCY",
    categories: ["banner-design", "logo-design"],
    image: "/Envobyte/ui6.png",
    logos: ["/Envobyte/seo.png"],
  },
  {
    id: 7,
    title: "LanghamTrading Profitabel Stock Picks",
    categories: ["ui-ux", "google-ads"],
    image: "/Envobyte/ui7.png",
    logos: ["/Envobyte/wordpress.png", "/Envobyte/seo.png"],
  },
  {
    id: 8,
    title: "Improve your Skill With This Way",
    categories: ["seo", "google-ads"],
    image: "/Envobyte/ui-1.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 9,
    title: "DIGITAL DESIGN AGENCY",
    categories: ["banner-design", "logo-design"],
    image: "/Envobyte/ui2.png",
    logos: ["/Envobyte/seo.png"],
  },
  {
    id: 10,
    title: "LanghamTrading Profitabel Stock Picks",
    categories: ["ui-ux", "google-ads"],
    image: "/Envobyte/ui3.png",
    logos: ["/Envobyte/wordpress.png", "/Envobyte/seo.png"],
  },
  {
    id: 11,
    title: "Improve your Skill With This Way",
    categories: ["seo", "google-ads"],
    image: "/Envobyte/ui4.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 12,
    title: "DIGITAL DESIGN AGENCY",
    categories: ["banner-design", "logo-design"],
    image: "/Envobyte/ui5.png",
    logos: ["/Envobyte/seo.png"],
  },
  {
    id: 13,
    title: "LanghamTrading Profitabel Stock Picks",
    categories: ["ui-ux", "google-ads"],
    image: "/Envobyte/ui6.png",
    logos: ["/Envobyte/wordpress.png", "/Envobyte/seo.png"],
  },
  {
    id: 14,
    title: "Improve your Skill With This Way",
    categories: ["seo", "google-ads"],
    image: "/Envobyte/ui2.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 15,
    title: "DIGITAL DESIGN AGENCY",
    categories: ["banner-design", "logo-design"],
    image: "/Envobyte/ui5.png",
    logos: ["/Envobyte/seo.png"],
  },
  {
    id: 16,
    title: "LanghamTrading Profitabel Stock Picks",
    categories: ["ui-ux", "google-ads"],
    image: "/Envobyte/ui7.png",
    logos: ["/Envobyte/wordpress.png", "/Envobyte/seo.png"],
  },
  {
    id: 17,
    title: "Improve your Skill With This Way",
    categories: ["seo", "google-ads"],
    image: "/Envobyte/ui3.png",
    logos: ["/Envobyte/wordpress.png"],
  },
  {
    id: 18,
    title: "DIGITAL DESIGN AGENCY",
    categories: ["banner-design", "logo-design"],
    image: "/Envobyte/ui4.png",
    logos: ["/Envobyte/seo.png"],
  },
];

export default portfolioData;
