import Header from "./Header";
import HeroSection from "./HeroSection";
import Footer from "./Footer";
import Services from "./Services";
import Details from "./Details";
import Portfolio from "./Portfolio";
import HowWeWork from "./HowWeWork";
import FrequentlyAskedQuestions from "./FrequentlyAskedQuestions";
import OurTeamMembers from "./OurTeamMembers";
import Reviews from "./Reviews";
export { default as Header } from "./Header";
export { default as HeroSection } from "./HeroSection";
export { default as Footer } from "./Footer";
export { default as Services } from "./Services";
export { default as Details } from "./Details";
export { default as Portfolio } from "./Portfolio";
export { default as HowWeWork } from "./HowWeWork";
export { default as FrequentlyAskedQuestions } from "./FrequentlyAskedQuestions";
export { default as OurTeamMembers } from "./OurTeamMembers";
export { default as Reviews } from "./Reviews";
